/* =====================================================
   KRIX MUSIC
   PART 1 / 2
===================================================== */

let transposeAmount = 0;

let mediaRecorder = null;
let audioChunks = [];
let audioBlob = null;

let recordingTimer = null;
let recordingSeconds = 0;


/* =====================================================
   GENERATE SONG
===================================================== */

async function generateSong() {

  const song =
    document.getElementById("songName")
      .value.trim();

  const artist =
    document.getElementById("artistName")
      .value.trim();

  const instrument =
    document.getElementById("instrument")
      .value;

  const lyrics =
    document.getElementById("lyricsInput")
      .value.trim();

  const status =
    document.getElementById(
      "generationStatus"
    );


  if (!song) {
    alert("Enter the song name.");
    return;
  }


  if (!artist) {
    alert("Enter the artist.");
    return;
  }


  status.textContent =
    "✨ KRIX is creating your music...";


  document.getElementById(
    "workspace"
  ).style.display = "block";


  document.getElementById(
    "outputSong"
  ).textContent = song;


  document.getElementById(
    "outputArtist"
  ).textContent = artist;


  const icons = {

    guitar: "🎸",
    piano: "🎹",
    flute: "🪈",
    ukulele: "🎵",
    violin: "🎻",
    keyboard: "🎹"

  };


  document.getElementById(
    "outputInstrument"
  ).textContent =

    `${icons[instrument]} ${
      instrument.charAt(0).toUpperCase()
      + instrument.slice(1)
    }`;


  document.getElementById(
    "sheetTitle"
  ).textContent = song;


  document.getElementById(
    "sheetArtist"
  ).textContent = artist;


  document.getElementById(
    "songContent"
  ).innerHTML = `

    <div class="empty-state">

      <div class="empty-icon">
        🪐
      </div>

      <p>
        KRIX is generating...
      </p>

    </div>

  `;


  try {

    const response =
      await fetch(
        "/api/generate",
        {

          method: "POST",

          headers: {
            "Content-Type":
              "application/json"
          },

          body: JSON.stringify({

            song: song,

            artist: artist,

            instrument: instrument,

            lyrics: lyrics

          })

        }
      );


    const data =
      await response.json();


    if (!response.ok) {

      throw new Error(
        data.error ||
        "KRIX generation failed."
      );
    }


    displaySong(data);


    status.textContent =
      "✅ Generated by KRIX";


  } catch (error) {

    console.error(error);


    document.getElementById(
      "songContent"
    ).innerHTML = `

      <div class="empty-state">

        <div class="empty-icon">
          ⚠️
        </div>

        <p>
          KRIX generation backend
          is not connected yet.
        </p>

        <p>
          Use Demo Mode to test
          the interface.
        </p>

      </div>

    `;


    status.textContent =
      "⚠️ KRIX backend unavailable.";
  }
}


/* =====================================================
   DISPLAY SONG
===================================================== */

function displaySong(data) {

  const content =
    document.getElementById(
      "songContent"
    );


  content.innerHTML = "";


  document.getElementById(
    "bpm"
  ).textContent =
    `${data.bpm || "--"} BPM`;


  document.getElementById(
    "sheetArtist"
  ).textContent =

    `${document.getElementById(
      "outputArtist"
    ).textContent} • Key: ${
      data.key || "Unknown"
    }`;


  if (
    !data.lines ||
    !Array.isArray(data.lines)
  ) {

    throw new Error(
      "Invalid KRIX response."
    );
  }


  data.lines.forEach(
    line => {

      const row =
        document.createElement(
          "div"
        );


      row.className =
        "song-line";


      row.innerHTML = `

        <div class="song-section">

          [${escapeHtml(
            line.section ||
            "Section"
          )}]

        </div>


        <div class="chords">

          ${escapeHtml(
            line.chords || ""
          )}

        </div>


        <div class="lyrics">

          ${escapeHtml(
            line.lyrics || ""
          )}

        </div>

      `;


      content.appendChild(row);

    }
  );


  transposeAmount = 0;


  document.getElementById(
    "transposeValue"
  ).textContent = "0";


  showMusicTab("chords");
}


/* =====================================================
   CHORDS / LYRICS
===================================================== */

function showMusicTab(type) {

  const chords =
    document.querySelectorAll(
      ".chords"
    );


  const lyrics =
    document.querySelectorAll(
      ".lyrics"
    );


  const chordsTab =
    document.getElementById(
      "chordsTab"
    );


  const lyricsTab =
    document.getElementById(
      "lyricsTab"
    );


  chordsTab.classList.remove(
    "active"
  );


  lyricsTab.classList.remove(
    "active"
  );


  if (type === "lyrics") {

    chords.forEach(
      item => {

        item.style.display =
          "none";

      }
    );


    lyrics.forEach(
      item => {

        item.style.display =
          "block";

      }
    );


    lyricsTab.classList.add(
      "active"
    );


  } else {

    /*
      Chords view shows both
      chords and lyrics.
    */

    chords.forEach(
      item => {

        item.style.display =
          "block";

      }
    );


    lyrics.forEach(
      item => {

        item.style.display =
          "block";

      }
    );


    chordsTab.classList.add(
      "active"
    );
  }
}


/* =====================================================
   TRANSPOSE
===================================================== */

const chordMap = {

  C: 0,
  "C#": 1,
  D: 2,
  "D#": 3,
  E: 4,
  F: 5,
  "F#": 6,
  G: 7,
  "G#": 8,
  A: 9,
  "A#": 10,
  B: 11

};


const chordNames = [

  "C",
  "C#",
  "D",
  "D#",
  "E",
  "F",
  "F#",
  "G",
  "G#",
  "A",
  "A#",
  "B"

];


function transposeChord(
  chord,
  amount
) {

  const match =
    chord.match(
      /^([A-G](?:#|b)?)(.*)$/
    );


  if (!match) {
    return chord;
  }


  let root =
    match[1];


  const rest =
    match[2];


  const flats = {

    Db: "C#",
    Eb: "D#",
    Gb: "F#",
    Ab: "G#",
    Bb: "A#"

  };


  if (root.includes("b")) {

    root =
      flats[root] || root;
  }


  if (!(root in chordMap)) {

    return chord;
  }


  let index =
    chordMap[root] + amount;


  index =
    ((index % 12) + 12) % 12;


  return (
    chordNames[index] +
    rest
  );
}


function transpose(amount) {

  transposeAmount += amount;


  document
    .querySelectorAll(".chords")
    .forEach(
      element => {

        const words =
          element.textContent
            .trim()
            .split(/\s+/);


        element.textContent =
          words
            .map(
              chord =>
                transposeChord(
                  chord,
                  amount
                )
            )
            .join(" ");

      }
    );


  document.getElementById(
    "transposeValue"
  ).textContent =

    transposeAmount > 0
      ? `+${transposeAmount}`
      : transposeAmount;
}


/* =====================================================
   COPY
===================================================== */

function copySheet() {

  const title =
    document.getElementById(
      "sheetTitle"
    ).textContent;


  const artist =
    document.getElementById(
      "sheetArtist"
    ).textContent;


  const content =
    document.getElementById(
      "songContent"
    ).innerText;


  navigator.clipboard
    .writeText(
      `${title}\n${artist}\n\n${content}`
    )


    .then(() => {

      alert(
        "✅ KRIX sheet copied!"
      );

    })


    .catch(() => {

      alert(
        "Unable to copy."
      );

    });
}/* =====================================================
   KRIX MUSIC
   PART 2 / 2
===================================================== */


/* =====================================================
   DEMO MODE
===================================================== */

function loadDemo() {

  const demoData = {

    bpm: 92,

    key: "C",

    lines: [

      {
        section: "Verse",
        chords: "C  G  Am  F",
        lyrics: "Walking through the night, chasing every light"
      },

      {
        section: "Verse",
        chords: "C  G  Am  F",
        lyrics: "Every little dream is coming into sight"
      },

      {
        section: "Chorus",
        chords: "F  G  C  Am",
        lyrics: "We can fly, we can rise, we can touch the sky"
      },

      {
        section: "Chorus",
        chords: "F  G  C  C",
        lyrics: "KRIX keeps the music alive"
      },

      {
        section: "Bridge",
        chords: "Am  F  C  G",
        lyrics: "Keep moving forward, never let it go"
      }

    ]

  };


  document.getElementById(
    "songName"
  ).value = "Midnight Dreams";


  document.getElementById(
    "artistName"
  ).value = "KRIX Original";


  document.getElementById(
    "instrument"
  ).value = "guitar";


  document.getElementById(
    "generationStatus"
  ).textContent =
    "✨ Demo loaded";


  document.getElementById(
    "workspace"
  ).style.display = "block";


  document.getElementById(
    "outputSong"
  ).textContent =
    "Midnight Dreams";


  document.getElementById(
    "outputArtist"
  ).textContent =
    "KRIX Original";


  document.getElementById(
    "outputInstrument"
  ).textContent =
    "🎸 Guitar";


  document.getElementById(
    "sheetTitle"
  ).textContent =
    "Midnight Dreams";


  displaySong(demoData);


  document.getElementById(
    "generationStatus"
  ).textContent =
    "✅ KRIX Demo Mode";
}


/* =====================================================
   MICROPHONE
===================================================== */

async function requestMicrophone() {

  try {

    const stream =
      await navigator.mediaDevices
        .getUserMedia({
          audio: true
        });


    mediaRecorder =
      new MediaRecorder(stream);


    audioChunks = [];


    mediaRecorder.ondataavailable =
      event => {

        if (event.data.size > 0) {

          audioChunks.push(
            event.data
          );

        }

      };


    mediaRecorder.onstop = () => {

      audioBlob =
        new Blob(
          audioChunks,
          {
            type:
              mediaRecorder.mimeType ||
              "audio/webm"
          }
        );


      const audioURL =
        URL.createObjectURL(
          audioBlob
        );


      const audio =
        document.getElementById(
          "recordedAudio"
        );


      audio.src =
        audioURL;


      audio.style.display =
        "block";


      document.getElementById(
        "downloadRecording"
      ).style.display =
        "inline-flex";


      document.getElementById(
        "deleteRecording"
      ).style.display =
        "inline-flex";

    };


    return true;

  } catch (error) {

    console.error(
      "Microphone error:",
      error
    );


    alert(
      "🎤 Microphone permission is required to record."
    );


    return false;
  }
}


/* =====================================================
   RECORDING
===================================================== */

async function toggleRecording() {

  const recordButton =
    document.getElementById(
      "recordButton"
    );


  /*
    First click:
    Ask for microphone permission.
  */

  if (!mediaRecorder) {

    const allowed =
      await requestMicrophone();


    if (!allowed) {
      return;
    }

  }


  /*
    START RECORDING
  */

  if (
    mediaRecorder.state ===
    "inactive"
  ) {

    audioChunks = [];


    mediaRecorder.start();


    recordingSeconds = 0;


    updateTimer();


    recordingTimer =
      setInterval(
        updateTimer,
        1000
      );


    recordButton.textContent =
      "⏹ Stop";


    recordButton.classList.add(
      "recording"
    );


    return;
  }


  /*
    STOP RECORDING
  */

  if (
    mediaRecorder.state ===
    "recording"
  ) {

    mediaRecorder.stop();


    clearInterval(
      recordingTimer
    );


    recordButton.textContent =
      "🎙 Record";


    recordButton.classList.remove(
      "recording"
    );

  }
}


/* =====================================================
   RECORDING TIMER
===================================================== */

function updateTimer() {

  const timer =
    document.getElementById(
      "recordingTimer"
    );


  const minutes =
    Math.floor(
      recordingSeconds / 60
    );


  const seconds =
    recordingSeconds % 60;


  timer.textContent =
    `${String(minutes).padStart(2, "0")}:${String(seconds).padStart(2, "0")}`;


  recordingSeconds++;
}


/* =====================================================
   DOWNLOAD RECORDING
===================================================== */

function downloadRecording() {

  if (!audioBlob) {

    alert(
      "No recording available."
    );

    return;
  }


  const url =
    URL.createObjectURL(
      audioBlob
    );


  const link =
    document.createElement(
      "a"
    );


  link.href = url;


  link.download =
    "KRIX-recording.webm";


  document.body.appendChild(
    link
  );


  link.click();


  link.remove();


  setTimeout(
    () => URL.revokeObjectURL(url),
    1000
  );
}


/* =====================================================
   DELETE RECORDING
===================================================== */

function deleteRecording() {

  audioBlob = null;


  const audio =
    document.getElementById(
      "recordedAudio"
    );


  audio.pause();


  audio.removeAttribute(
    "src"
  );


  audio.load();


  audio.style.display =
    "none";


  document.getElementById(
    "downloadRecording"
  ).style.display =
    "none";


  document.getElementById(
    "deleteRecording"
  ).style.display =
    "none";


  document.getElementById(
    "recordingTimer"
  ).textContent =
    "00:00";


  recordingSeconds = 0;
}


/* =====================================================
   HTML ESCAPE
===================================================== */

function escapeHtml(value) {

  return String(value)

    .replace(
      /&/g,
      "&amp;"
    )

    .replace(
      /</g,
      "&lt;"
    )

    .replace(
      />/g,
      "&gt;"
    )

    .replace(
      /"/g,
      "&quot;"
    )

    .replace(
      /'/g,
      "&#039;"
    );
}


/* =====================================================
   KRIX READY
===================================================== */

console.log(
  "🚀 KRIX Music Assistant loaded."
);